import { Inter } from "next/font/google";
import Script from "next/script";
import Head from 'next/head';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>One Page App</title>
        <meta name="description" content="One Page Application using Next.js and Bootstrap" />
      </Head>

      <body className={inter.className}>
        {children}
      </body>
      <Script src="https://kit.fontawesome.com/e3374afba4.js" crossOrigin="anonymous" />

    </html>
  );
}