import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css"
import Script from "next/script";
import Head from 'next/head';
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>One Page App</title>
        <meta name="description" content="One Page Application using Next.js and Bootstrap" />
        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
            integrity="sha384-DyZv1W4G2vF4q1Fz7Zc9iH0n3h3ae2m0g4f3f3W3C2n3P1hYl0vzzPzG5Xw6hE"
            crossOrigin="anonymous"
          />
      </Head>

      <body className={inter.className}>
        <Header></Header>
        {children}
      </body>
      <Script src="https://kit.fontawesome.com/e3374afba4.js" crossOrigin="anonymous" />
      
    </html>
  );
}
