import { Inter } from "next/font/google";
import "./globals.css";
import { open_sans } from "@/utils/fonts";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import Script from "next/script";
import "/public/libs/bootstrap/css/bootstrap.min.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { locale } }) {
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={open_sans.className}>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
        <Script
          src="https://kit.fontawesome.com/e3374afba4.js"
          crossOrigin="anonymous"
        />
        <Script src="libs/bootstrap/js/bootstrap.min.js" />
      </body>
    </html>
  );
}
